export const AUDIO_FEEDBACK = Object.freeze({
  masterVolume: 0.26,
  sounds: Object.freeze({
    correctKey: Object.freeze({
      type: 'tone',
      frequency: 740,
      endFrequency: 880,
      durationMs: 46,
      volume: 0.13,
      wave: 'sine',
    }),
    wrongKey: Object.freeze({
      type: 'tone',
      frequency: 180,
      endFrequency: 118,
      durationMs: 95,
      volume: 0.18,
      wave: 'triangle',
    }),
    wordCompleted: Object.freeze({
      type: 'arpeggio',
      frequencies: Object.freeze([523, 659, 784]),
      stepMs: 46,
      volume: 0.17,
      wave: 'sine',
    }),
    playerDamage: Object.freeze({
      type: 'tone',
      frequency: 160,
      endFrequency: 72,
      durationMs: 170,
      volume: 0.22,
      wave: 'sawtooth',
    }),
    dangerHint: Object.freeze({
      type: 'warning-beeps',
      frequency: 760,
      endFrequency: 620,
      beepDurationMs: 190,
      gapMs: 85,
      count: 3,
      volume: 0.32,
      wave: 'square',
    }),
    levelComplete: Object.freeze({
      type: 'arpeggio',
      frequencies: Object.freeze([392, 523, 659, 784]),
      stepMs: 62,
      volume: 0.18,
      wave: 'triangle',
    }),
    stageComplete: Object.freeze({
      type: 'arpeggio',
      frequencies: Object.freeze([392, 494, 587, 784, 988]),
      stepMs: 70,
      volume: 0.18,
      wave: 'sine',
    }),
    gameOver: Object.freeze({
      type: 'arpeggio',
      frequencies: Object.freeze([294, 220, 165]),
      stepMs: 96,
      volume: 0.19,
      wave: 'triangle',
    }),
    toggle: Object.freeze({
      type: 'tone',
      frequency: 520,
      endFrequency: 660,
      durationMs: 70,
      volume: 0.12,
      wave: 'sine',
    }),
  }),
});
